name: Sync with Upstream

env:
  UPSTREAM_REPO_URL: https://github.com/PokeMiners/pogo_assets.git

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Upstream Remote
        run: git remote add upstream ${{env.UPSTREAM_REPO_URL}}
        
      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/master

      - name: Push Changes
        run: git push origin master
